package com.squareetlabs.verifactu.contracts;

import java.time.LocalDate;

/**
 * Contract that models must implement to request the AEAT annulment
 * ("anulación") of a previously generated billing record
 * ({@code RegistroFacturacionAnulacionType}).
 * <p>
 * An annulment record does NOT delete or modify the original invoice: it
 * is itself a new, chained billing record that tells the AEAT that a
 * previous record ("de alta") must be considered void. This is the
 * mechanism defined by the AEAT for retracting a record - e.g. one that was
 * sent with wrong data, sent by mistake, or was never actually registered
 * at the AEAT (see "Anulación de un registro de facturación" in the
 * VERI*FACTU functional spec). It is a different operation from a
 * <em>rectificativa</em> (R1-R5), which corrects an invoice from a fiscal
 * perspective by issuing a brand-new invoice: use {@link VeriFactuInvoice}
 * with {@code invoiceType = R1..R5} for that case instead.
 */
public interface VeriFactuAnnulment {

    /**
     * Get the invoice number/series of the ORIGINAL invoice being annulled
     * ({@code IDFactura.NumSerieFacturaAnulada}).
     *
     * @return String
     */
    String getInvoiceNumber();

    /**
     * Get the issue date of the ORIGINAL invoice being annulled
     * ({@code IDFactura.FechaExpedicionFacturaAnulada}).
     *
     * @return LocalDate
     */
    LocalDate getIssueDate();

    /**
     * Get the previous record hash for chaining ({@code Encadenamiento.RegistroAnterior.Huella}).
     * Return null for the first record in the chain.
     *
     * @return String or null
     */
    String getPreviousHash();

    /**
     * Get the external reference (optional). Maps to {@code RefExterna}.
     *
     * @return String or null
     */
    default String getExternalReference() {
        return null;
    }

    /**
     * Whether the invoice being annulled was never actually registered at
     * the AEAT (e.g. it was rejected for unrecoverable errors, or it was
     * generated while the system was not yet capable of remitting
     * verifiable records). Maps to {@code SinRegistroPrevio = "S"}.
     * <p>
     * Defaults to {@code false} (the common case: the invoice being
     * annulled IS registered at the AEAT).
     *
     * @return boolean
     */
    default boolean isNotRegisteredAtAeat() {
        return false;
    }

    /**
     * Whether this annulment record is a resubmission that corrects a
     * previous annulment record for the SAME invoice that the AEAT
     * rejected. Maps to {@code RechazoPrevio = "S"}.
     * <p>
     * Defaults to {@code false}.
     *
     * @return boolean
     */
    default boolean isRetryAfterRejection() {
        return false;
    }

    /**
     * Who generated this annulment record, when it was NOT generated by
     * the "obligado a expedir factura" itself. Maps to
     * {@code RegistroFacturacionAnulacionType.GeneradoPor}.
     * <p>
     * Valid values:
     * <ul>
     * <li>{@code null} (default): generated by the obligado itself. Both
     * {@code GeneradoPor} and {@code Generador} are omitted.</li>
     * <li>{@code "T"} (Tercero): generated by a third party (e.g. Odei)
     * acting on behalf of the obligado. Requires {@link #getGeneratorName()}
     * and {@link #getGeneratorTaxId()}.</li>
     * <li>{@code "D"} (Destinatario): generated by the recipient of the
     * original invoice (self-billing scenarios). Requires
     * {@link #getGeneratorName()} and {@link #getGeneratorTaxId()}.</li>
     * </ul>
     *
     * @return "T", "D" or null
     */
    default String getGeneratedBy() {
        return null;
    }

    /**
     * Name of the third party/recipient that generated this annulment
     * record (required when {@link #getGeneratedBy()} is {@code "T"} or
     * {@code "D"}). Maps to {@code Generador.NombreRazon}.
     *
     * @return String or null
     */
    default String getGeneratorName() {
        return null;
    }

    /**
     * Tax ID (NIF) of the third party/recipient that generated this
     * annulment record (required when {@link #getGeneratedBy()} is
     * {@code "T"} or {@code "D"}). Maps to {@code Generador.NIF}.
     *
     * @return String or null
     */
    default String getGeneratorTaxId() {
        return null;
    }
}
